drop table TaskClassRooms
drop table TaskEquipments
drop table Tasks
drop table AdministrativeActivities
drop table StudentCircles
drop table DidacticActivities
drop table ResearchActivities
drop table ResearchProjectPhases
drop table ResearchProjects
drop table ActivityEquipments
drop table ActivityClassRooms
drop table Activities
drop table TeamMembers
drop table Teams
drop table StudyProgrammes
drop table ClassRoomEquipment
drop table ClassRooms
drop table Equipments
drop table FinancialResources
drop table Members
