insert into ClassRooms VALUES( '2/I', 'Sala Nicolae Iorga, Cladirea Centrala, etaj 1 (Str. M. Kogalniceanu)' )
insert into ClassRooms VALUES( '5/I', 'Sala Tiberiu Popoviciu, Cladirea Centrala, etaj 1 (Str. M. Kogalniceanu)' )
insert into ClassRooms VALUES( '6/II', 'Sala Gheorghe Calugareanu, Cladirea Centrala, etaj 2 (Str. M. Kogalniceanu)' )
insert into ClassRooms VALUES( '7/I', 'Sala D.V. Ionescu, Cladirea Centrala, etaj 1 (Str. M. Kogalniceanu)' )
insert into ClassRooms VALUES( '9/I', 'Cladirea Centrala, etaj 1 (Str. M. Kogalniceanu)' )
insert into ClassRooms VALUES( 'A311', 'Cladirea Avram Iancu, etaj 3 (Str. A. Iancu)' )
insert into ClassRooms VALUES( 'A312', 'Cladirea Avram Iancu, etaj 3 (Str. A. Iancu)' )
insert into ClassRooms VALUES( 'A313', 'Cladirea Avram Iancu, etaj 3 (Str. A. Iancu)' )
insert into ClassRooms VALUES( 'A321', 'Cladirea Avram Iancu, etaj 3 (Str. A. Iancu)' )
insert into ClassRooms VALUES( 'A322', 'Cladirea Avram Iancu, etaj 3 (Str. A. Iancu)' )
insert into ClassRooms VALUES( 'A323', 'Cladirea Avram Iancu, etaj 3 (Str. A. Iancu)' )
insert into ClassRooms VALUES( 'e', 'Cladirea Mathematicum, etaj 1 (str. Ploiesti)' )
insert into ClassRooms VALUES( 'gamma', 'Cladirea Mathematicum (str. Ploiesti)' )
insert into ClassRooms VALUES( 'lambda', 'Cladirea Mathematicum  (str. Ploiesti)' )
insert into ClassRooms VALUES( 'Multimedia', 'Cladirea Mathematicum (str. Ploiesti)' )
insert into ClassRooms VALUES( 'phi', 'Cladirea Mathematicum (str. Ploiesti)' )
insert into ClassRooms VALUES( 'pi', 'Cladirea Mathematicum, parter (str. Ploiesti)' )
insert into ClassRooms VALUES( 'theta', 'Cladirea Mathematicum (str. Ploiesti)' )
insert into ClassRooms VALUES( 'C310', 'Campus, etaj 3 (str. T. Mihali)' )
insert into ClassRooms VALUES( 'C335', 'Campus, etaj 3 (str. T. Mihali)' )
insert into ClassRooms VALUES( 'C509', 'Campus, etaj 5 (str. T. Mihali)' )
insert into ClassRooms VALUES( 'C510', 'Campus, etaj 5 (str. T. Mihali)' )
insert into ClassRooms VALUES( 'C512', 'Campus, etaj 5 (str. T. Mihali)' )
insert into ClassRooms VALUES( 'C514', 'Campus, etaj 5 (str. T. Mihali)' )
insert into ClassRooms VALUES( 'L301', 'Campus, etaj 3 (str. T. Mihali)' )
insert into ClassRooms VALUES( 'L302', 'Campus, etaj 3 (str. T. Mihali)' )
insert into ClassRooms VALUES( 'L306', 'Campus, etaj 3 (str. T. Mihali)' )
insert into ClassRooms VALUES( 'L307', 'Campus, etaj 3 (str. T. Mihali)' )
insert into ClassRooms VALUES( 'L308', 'Campus, etaj 3 (str. T. Mihali)' )
insert into ClassRooms VALUES( 'L320', 'Campus, etaj 3 (str. T. Mihali) - Laborator la Fac. de Stiinte Economice' )
insert into ClassRooms VALUES( 'L336', 'Campus, etaj 3 (str. T. Mihali)' )
insert into ClassRooms VALUES( 'L338', 'Campus, etaj 3 (str. T. Mihali)' )
insert into ClassRooms VALUES( 'L339', 'Campus, etaj 3 (str. T. Mihali)' )
insert into ClassRooms VALUES( 'L343', 'Campus, etaj 3 (str. T. Mihali)' )
insert into ClassRooms VALUES( 'Obs', 'Observatorul Astronomic (str. Ciresilor)' )
insert into ClassRooms VALUES( 'Chimie', 'Amfiteatru, Facultatea de Chimie (str. Arany Janos 11)' )
insert into ClassRooms VALUES( 'Aerobic', 'Sala Aerobic, Parcul Iuliu Hatieganu' )
insert into ClassRooms VALUES( 'Atletism', 'Sala Atletism, Parcul Iuliu Hatieganu' )
insert into ClassRooms VALUES( 'Ge', 'V Geleriu' )
insert into ClassRooms VALUES( 'Ro', 'Gh. Roman' )
insert into ClassRooms VALUES( 'Catedra', 'Sediul unde are birou indrumatorul' )
insert into ClassRooms VALUES( 'Horia 7/10', 'Str.Horia nr.7, sala 10 (Fac.Litere)' )
insert into ClassRooms VALUES( 'NI', 'Strada Corneliu Coposu, nr. 167A, http://romania.ni.com/' )